harnessApiVersion: '1.0'
type: ROLLING
concurrencyStrategy: INFRA
envName: prod
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - PFIVcv84TVW6OEpQEDvmGw
phases:
- type: KUBERNETES
  computeProviderName: K8S Diego GKE
  daemonSet: false
  infraDefinitionName: ring-0
  name: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: SHELL_SCRIPT
      name: Stable Instance Config Setup
      properties:
        commandPath: null
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        includeInfraSelectors: true
        publishAsVar: false
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        templateExpressions: null
        timeoutMillis: 600000
      templateUri: Harness SE/Diego/Canary Instance Config Setup:latest
      templateVariables:
      - name: logsPerMinute
        value: '600'
      - name: logErrorRate
        value: '500'
      - name: logErrorMessage
        value: UnknownException
      - name: callsPerMinute
        value: '600'
      - name: errorRate
        value: '500'
      - name: minErrorValue
        value: '0.4'
      - name: maxErrorValue
        value: '0.7'
      - name: shouldDoDelayedCalls
        value: 'true'
    stepsInParallel: false
  provisionNodes: false
  serviceName: cv-demo
  statefulSet: false
  templateExpressions:
  - expression: ${InfraDefinition_KUBERNETES}
    fieldName: infraDefinitionId
    metadata:
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
rollbackPhases:
- type: KUBERNETES
  computeProviderName: K8S Diego GKE
  daemonSet: false
  infraDefinitionName: ring-0
  name: Rollback Rolling
  phaseNameForRollback: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: cv-demo
  statefulSet: false
  templateExpressions:
  - expression: ${InfraDefinition_KUBERNETES}
    fieldName: infraDefinitionId
    metadata:
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
templateExpressions:
- expression: ${Environment}
  fieldName: envId
  metadata:
  - name: relatedField
    value: ${InfraDefinition_KUBERNETES}
  - name: entityType
    value: ENVIRONMENT
- expression: ${InfraDefinition_KUBERNETES}
  fieldName: infraDefinitionId
  metadata:
  - name: relatedField
  - name: entityType
    value: INFRASTRUCTURE_DEFINITION
templatized: true
userVariables:
- type: ENTITY
  description: Variable for Environment entity
  fixed: false
  mandatory: true
  name: Environment
- type: ENTITY
  description: Variable for Infrastructure Definition entity in Rollback Rolling
  fixed: false
  mandatory: true
  name: InfraDefinition_KUBERNETES
